import dash
from dash import dcc, html
import dash_bootstrap_components as dbc

eng_incum_list=['AGREEMENT FOR SALE AND PURCHASE',
 'AGREEMENT FOR SALE AND PURCHASE WITH PLAN',
 'AGREEMENT FOR SUBSALE AND PURCHASE',
 'AGREEMENT FOR SUBSALE AND SUBPURCHASE',
 'APPROVAL LETTER',
 'ASSENT',
 'ASSIGNMENT',
 'ASSIGNMENT OF RENTAL',
 'ASSIGNMENT WITH PLAN',
 'CANCELLATION AGREEMENT',
 'CARBON COPY OF PRELIMINARY SALE AND PURCHASE AGREEMENT',
 'CARBON COPY OF PROVISIONAL AGREEMENT FOR SALE AND PURCHASE',
 'CERTIFICATE OF COMPLIANCE',
 'CERTIFICATE OF EXEMPTION FROM ESTATE DUTY',
 'CERTIFICATE OF REGISTRATION OF DEATH',
 'CERTIFICATE UNDER S.33(1) OF THE BUILDINGS ORDINANCE',
 'CERTIFIED COPY OF AN ENTRY IN A REGISTER OF DEATH',
 'CERTIFIED COPY OF CERTIFICATE OF DEATH',
 'CERTIFIED COPY OF DEATH CERTIFICATE',
 'CERTIFIED COPY OF LETTER OF DETERMINATION',
 'CERTIFIED TRUE COPY OF DEATH CERTIFICATE',
 'CHINESE PROVISIONAL AGREEMENT FOR SALE AND PURCHASE',
 'CONFIRMATORY RELEASE',
 'CONSENT LETTER',
 'CONSENT TO ASSIGN',
 'DEATH CERTIFICATE',
 'DEED OF ASSENT',
 'DEED OF ASSIGNMENT',
 'DEED OF ASSIGNMENT OF RENTAL INCOME',
 'DEED OF FAMILY ARRANGEMENT',
 'DEED OF GIFT',
 'DEED OF LOAN',
 'DEED OF MUTUAL COVENANT AND MANAGEMENT AGREEMENT WITH PLAN',
 'DEED OF MUTUAL COVENANT INCORPORATING MANAGEMENT AGREEMENT WITH PLAN',
 'DEED OF RECTIFICATION',
 'DEED OF RELEASE',
 'DEED OF SEVERANCE',
 'DEED POLL',
 'DUPLICATE OF UNDERTAKING LETTER',
 'EQUITABLE MORTGAGE',
 'FINAL RELEASE',
 'FINANCE UNDERTAKING',
 'FIRE SAFETY COMPLIANCE ORDER UNDER S.6(1) OF FIRE SAFETY (BUILDINGS) ORDINANCE (CHAPTER 572)',
 'FIRST CHARGE',
 'FIRST EQUITABLE MORTGAGE',
 'FIRST LEGAL CHARGE',
 'FIRST LEGAL CHARGE/MORTGAGE',
 'FOURTH MORTGAGE',
 'FURTHER CHARGE',
 'GOVERNMENT NOTICE',
 'IRREVOCABLE POWER OF ATTORNEY',
 'LEGAL CHARGE',
 'LEGAL CHARGE/MORTGAGE',
 'LETTER FOR REMOVAL OF ALIENATION RESTRICTIONS',
 'LETTER OF COMPLIANCE',
 'LETTER OF NOMINATION',
 'LETTER OF REMOVAL OF ALIENATION RESTRICTIONS',
 'LETTER OF WITHDRAWAL',
 'LETTERS OF ADMINISTRATION',
 'LETTERS OF ADMINISTRATION DE BONIS NON',
 'LOAN AGREEMENT',
 'MEMORANDUM FOR SALE AND PURCHASE',
 'MEMORANDUM OF AGREEMENT FOR SALE AND PURCHASE',
 'MEMORANDUM OF CHARGE',
 'MEMORANDUM OF DETERMINATION',
 'MEMORANDUM OF DISCHARGE',
 'MEMORANDUM OF RELEASE',
 'MEMORANDUM OF SALE',
 'MEMORANDUM OF SALE AND PURCHASE',
 'MEMORANDUM OF SATISFACTION',
 'MEMORIAL OF SATISFACTION UNDER S.33(10) OF THE BUILDINGS ORDINANCE',
 'MORTGAGE',
 'MORTGAGE DEED',
 'MORTGAGE TO SECURE GENERAL BANKING FACILITIES',
 'MORTGAGE/LEGAL CHARGE',
 'NO OBJECTION LETTER',
 'NOMINATION',
 'NOTICE OF SEVERANCE',
 'NOTICE OF SEVERANCE OF JOINT TENANCY',
 'NOTICE UNDER S.24C(1) OF THE BUILDINGS ORDINANCE',
 'NOTICE UNDER S.30B(3) OF THE BUILDINGS ORDINANCE',
 'NOTICE UNDER S.30C(3) OF THE BUILDINGS ORDINANCE',
 'NOTIFICATION LETTER OF COMPLETION OF WORKS',
 'NOTIFICATION LETTER OF COMPLETION OF WORKS RELATING TO ORDER',
 'OCCUPATION PERMIT',
 'ORDER',
 'ORDER UNDER S.24(1) OF THE BUILDINGS ORDINANCE',
 'ORDER UNDER S.24(1) OF THE BUILDINGS ORDINANCE WITH PLAN',
 'ORDER UNDER S.26 OF THE BUILDINGS ORDINANCE',
 'ORDER UNDER S.26 OF THE BUILDINGS ORDINANCE WITH PLAN',
 'ORDER UNDER S.26A(1) OF THE BUILDINGS ORDINANCE',
 'ORDER UNDER S.26A(1) OF THE BUILDINGS ORDINANCE WITH PLAN',
 'ORDER UNDER S.27A OF THE BUILDINGS ORDINANCE WITH PLAN',
 'ORDER UNDER S.28(3) OF THE BUILDINGS ORDINANCE',
 'ORDER UNDER S.28(3) OF THE BUILDINGS ORDINANCE WITH PLAN',
 'PARTIAL RELEASE',
 'POWER OF ATTORNEY',
 'PRELIMINARY AGREEMENT FOR SALE AND PURCHASE',
 'PRELIMINARY SALE AND PURCHASE AGREEMENT',
 'PROBATE',
 'PROVISIONAL AGREEMENT FOR SALE AND PURCHASE',
 'RECEIPT ON DISCHARGE',
 'RECEIPT ON DISCHARGE OF A CHARGE',
 'RELEASE',
 'RENT ASSIGNMENT',
 'RENTAL ASSIGNMENT',
 'REREGISTRATION OF AGREEMENT FOR SALE AND PURCHASE MEMORIAL',
 'REREGISTRATION OF ASSIGNMENT MEMORIAL',
 'REVERSE MORTGAGE',
 'SALE AND PURCHASE AGREEMENT',
 'SATISFACTION LETTER',
 "SEALED COPY OF BANKRUPTCY ORDER ON DEBTOR'S PETITION",
 'SEALED COPY OF CHARGING ORDER ABSOLUTE',
 'SEALED COPY OF CHARGING ORDER: NOTICE TO SHOW CAUSE',
 'SEALED COPY OF ORDER',
 'SEALED COPY OF WRIT OF SUMMONS',
 'SECOND EQUITABLE MORTGAGE',
 'SECOND LEGAL CHARGE',
 'SECOND LEGAL CHARGE/MORTGAGE',
 'SECOND MORTGAGE',
 'SECOND SUPPLEMENTAL STATUTORY DECLARATION',
 'STATUTORY DECLARATION',
 'SUBCHARGE/SUBMORTGAGE',
 'SUBDEED OF MUTUAL COVENANT AND MANAGEMENT AGREEMENT WITH PLAN',
 'SUBDEED OF MUTUAL COVENANT WITH PLAN',
 'SUBMORTGAGE',
 'SUPERSEDING NOTICE UNDER S.30B(3) OF THE BUILDINGS ORDINANCE',
 'SUPERSEDING NOTICE UNDER S.30C(3) OF THE BUILDINGS ORDINANCE',
 'SUPERSEDING ORDER UNDER S.24(1) OF THE BUILDINGS ORDINANCE',
 'SUPERSEDING ORDER UNDER S.24(1) OF THE BUILDINGS ORDINANCE WITH PLAN',
 'SUPERSEDING ORDER UNDER S.26 OF THE BUILDINGS ORDINANCE',
 'SUPPLEMENTAL AGREEMENT',
 'SUPPLEMENTAL STATUTORY DECLARATION',
 'TENANCY AGREEMENT',
 'THIRD LEGAL CHARGE',
 'THIRD MORTGAGE',
 'THREE-PARTY MORTGAGE DEED',
 'TRANSFER OF MORTGAGE',
 'TRIPARTITE EQUITABLE MORTGAGE',
 'TRIPARTITE LEGAL CHARGE/MORTGAGE',
 'TRIPARTITE MORTGAGE/LEGAL CHARGE',
 'TRIPARTITE SECOND LEGAL CHARGE/MORTGAGE',
 'TWO-PARTY MORTGAGE DEED',
 'UNDERTAKING',
 'UNDERTAKING LETTER',
 'WAIVER LETTER']
zh_incum_list=[
    '買賣協議',
    '附有平面圖的買賣協議',
    '轉售和購買協議',
    '轉售和次買協議',
    '批准信函',
    '同意書',
    '轉讓',
    '租金轉讓',
    '附有平面圖的轉讓',
    '解約協議',
    '初步買賣協議的影印本',
    '臨時買賣協議的影印本',
    '合規證書',
    '免徵遺產稅證書',
    '死亡登記證書',
    '根據建築物條例第33(1)條的證書',
    '死亡登記簿副本',
    '死亡證書的認證副本',
    '死亡證書的認證副本',
    '判決書的認證副本',
    '死亡證書的真實副本',
    '中文臨時買賣協議',
    '確認解除',
    '同意書',
    '轉讓同意書',
    '死亡證書',
    '同意書',
    '轉讓契約',
    '租金收入轉讓契約',
    '家庭安排契約',
    '贈與契約',
    '貸款契約',
    '相互承諾和管理協議附有平面圖',
    '相互承諾和管理協議附有平面圖',
    '糾正契約',
    '解除契約',
    '分割契約',
    '宣誓書',
    '保證信函副本',

    '公平抵押',
    '最後解除',
    '融資承諾',
    '根據消防安全(建築物)條例第6(1)條的消防安全合規令(第572章)',
    '第一順位權',
    '第一順位公平抵押',
    '第一順位法定抵押',
    '第一順位法定抵押',
    '第四順位抵押',
    '進一步抵押',
    '政府公告',
    '不可撤銷的授權書',
    '法定抵押',
    '法定質權',
    '解除限制轉讓信函',
    '合規信函',
    '提名信函',
    '解除限制轉讓信函',
    '撤回信函',
    '授遺狀副本',
    '未授遺狀遺產繼續管理書副本',
    '貸款協議',
    '買賣備忘錄',
    '買賣協議備忘錄',
    '抵押備忘錄',
    '裁決備忘錄',
    '解除備忘錄',
    '解除備忘錄',
    '銷售備忘錄',
    '買賣備忘錄',
    '滿意備忘錄',
    '根據建築物條例第33(10)條的滿意紀念碑',
    '抵押',
    '抵押契約',
    '抵押以擔保一般銀行業務',
    '抵押/法定質權',

    '無異議信函',
    '提名',
    '分割通知書',
    '共同業權分割通知書',
    '根據建築物條例第24C(1)條的通知書',
    '根據建築物條例第30B(3)條的通知書',
    '根據建築物條例第30C(3)條的通知書',
    '工程完成通知書',
    '與命令相關的工程完成通知書',
    '使用許可證',
    '命令',
    '根據建築物條例第24(1)條的命令',
    '附有平面圖的建築物條例第24(1)條的命令',
    '根據建築物條例第26條的命令',
    '附有平面圖的建築物條例第26條的命令',
    '根據建築物條例第26A(1)條的命令',
    '附有平面圖的建築物條例第26A(1)條的命令',
    '根據建築物條例第27A條的命令附有平面圖',
    '根據建築物條例第28(3)條的命令',
    '附有平面圖的建築物條例第28(3)條的命令',
    '部分解除',
    '授權書',
    '初步買賣協議',
    '初步買賣協議',
    '遺囑認證',
    '臨時買賣協議',
    '解除收據',
    '解除抵押收據',
    '解除',
    '租金轉讓',
    '租金轉讓',
    '重新登記買賣協議紀錄',
    '重新登記轉讓紀錄',
    '逆向按揭',

    '買賣協議',
    '滿意信函',
    '依債務人申請的破產命令封存副本',
    '確定的質權封存副本',
    '質權封存副本：展示理由通知',
    '命令的封存副本',
    '債務狀的封存副本',
    '第二順位權益抵押',
    '第二順位法定質權',
    '第二順位法定質權/抵押',
    '第二順位抵押',
    '第二補充法定聲明',
    '法定聲明',
    '次級轉讓/次級抵押',
    '相互承諾和管理協議附有平面圖',
    '相互承諾協議附有平面圖',
    '次級抵押',
    '根據建築物條例第30B(3)條的修改通知書',
    '根據建築物條例第30C(3)條的修改通知書',
    '根據建築物條例第24(1)條的修改命令',
    '根據建築物條例第24(1)條的修改命令附有平面圖',
    '根據建築物條例第26條的修改命令',
    '補充協議',
    '補充法定聲明',
    '租賃協議',
    '第三順位法定質權',
    '第三順位抵押',
    '三方按揭契書',
    '抵押轉讓',
    '三方順位權益抵押',
    '三方法定質權/抵押',
    '三方抵押/法定質權',
    '三方次級法定質權/抵押',
    '雙方按揭契書',
    '保證',
    '保證信函',
    '豁免書'
]
eng_zh_incum_pairs= zip(eng_incum_list, zh_incum_list)

dash.register_page(__name__, path='/zh',title='產權負擔字典')

layout = [dbc.Row(
        dbc.Col(html.P(
                    html.A("Eng", href='/'
                         )
                ,className='text-end'),

        width=10)

    ),

    dbc.Row([

        dbc.Col([
            dcc.Markdown('輸入產權負擔名稱:'),
            dcc.Dropdown(id='my_dpdn_zh', multi=False, placeholder='請輸入',
                         options=[{'label': b, 'value': a}
                                  for a, b in eng_zh_incum_pairs],
                         ),
            #dcc.Graph(id='line-fig', figure={})
            dcc.Markdown(id='simple_text_zh', children= '{}'.format(''), style={"margin-top": "25px"} ),
            # dbc.Collapse(
            #         dbc.CardBody("Because it's a lot better than a hotdog."),
            #         id="collapse_zh", is_open=True
            # ),

            html.Div(#html.H6("Product: a beautiful Pizza reheated after a day in the fridge, for $99"),
                     style={"text-align":"center"}),
                html.Hr(),
                dbc.CardHeader(
                        dbc.Button(
                            "了解更多",
                            color="link",
                            id="button-question-1",
                        )
                ),






                dbc.Collapse(
                    dbc.CardBody(children="請先填入想查詢的產權負擔",),
                    id="collapse_zh", is_open=False
                ),

            html.Br(),
            html.Label(
                ['備註:'
                 '本字典僅供一般參考之用，並不構成提供任何專業意見。購買二手樓可能涉及複雜的法律問題，讀者在做出任何決策前應審慎考慮尋求相關專業人士的建議。'],

            ),
                html.Hr(),


                dbc.CardHeader(
                    [html.H5(
                        "需要更個人化的咨詢服務?",
                        #color="link",
                        id="personal_advice_header_zh",
                    ),

                    html.Label(
                        ['可', html.A('按此', href='https://www.proinfotech.net/contact/',target="_blank"), '聯絡我們的專業團隊。'],
                        id="advice_sent_zh",
                        )
                    ]


                ),





        ],  # width={'size':5, 'offset':1, 'order':1},
            xs=12, sm=12, md=12, lg=5, xl=5
        ),
    ],
justify='center')
    ]



